#! /bin/sh
gap=5
export gap

sxhkd &
ulauncher --hide-window --no-window-shadow &
nitrogen --restore &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &
[ -x ~/.cargo-target/release/buzz ] && ~/.cargo-target/release/buzz &
if [ -x ~/.cargo-target/release/keybase-chat-notifier ]; then
	keybase chat api-listen | ~/.cargo-target/release/keybase-chat-notifier &
fi
psensor &

bspc monitor -d I II III IV V 
###This creates and names desktops for multiple monitors.
workspaces_multimonitor &

bspc config border_width         1
bspc config window_gap           gap
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

bspc rule -a firefoxdeveloperedition desktop='^1'
# https://github.com/baskerville/bspwm/issues/291
# only works due to https://github.com/dasJ/spotifywm
bspc rule -a Spotify desktop='^6' state=pseudo_tiled
bspc rule -a ulauncher focus=on
bspc rule -a sxiv state=floating center=true
bspc rule -a polybar border=off manage=off

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config leaf_monocle true
bspc config adaptative_raise true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true

#Settings for manual splitting
bspc config auto_alternate true
bspc config auto_cancel true
bspc config split_ratio         0.52

bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 
###This creates and names desktops for multiple monitors.
workspaces_multimonitor &

bspc rule -a firefox desktop=I
bspc desktop I --layout monocle
bspc desktop II --layout monocle


##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##  This script balances all windows when new one is spawned 
#euclid_balancer &

##Edge-switcher switches to next workspace when moves moves to the 
##edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window

##Autostart apps
#Keybindings daemon
#sxhkd &
#Source autostartfile. Uncomment this if you use bspwm-git
#. $HOME/.config/bspwm/autostart

